# Generated by Django 2.2.4 on 2019-08-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsbycategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
